name: 'Fix Version Gaps'
description: 'Fixes gaps in version labels after a version bump'
inputs:
  github_token:
    description: An oauth token that will be used to create the backport pull requests and perform other operations
    required: true
runs:
  using: 'node24'
  main: 'index.js'
branding:
  icon: git-branch
  color: green
