env:
  GITHUB_COMMIT_STATUS_ENABLED: 'true'
  GITHUB_COMMIT_STATUS_CONTEXT: 'buildkite'
steps:
  - label: 'Pre-Build'
    command: .buildkite/pre-build.sh
  - wait
  - label: 'Pull Request CI'
    command: .buildkite/pr.sh
    plugins:
      - docker#v3.8.0:
          image: 'node:16.13'
          workdir: /
          propagate-uid-gid: true
          volumes: ['/.npm', '/.yarn']
  - wait: ~
    continue_on_failure: true
  - label: 'Post-Build'
    command: .buildkite/post-build.sh
